In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
import seaborn as sns
from sklearn.decomposition import PCA
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.base import clone
from itertools import combinations
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
import sys
from scipy.stats import ttest_ind, zscore
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC
import copy
import json

In [2]:
df_2017 = pd.read_csv("../data/afl_results_2017.csv")
#print(df_2017.shape)
df_2018 = pd.read_csv("../data/afl_results_2018.csv")
#print(df_2018.shape)
df_2019 = pd.read_csv("../data/afl_results_2019.csv")
#print(df_2019.shape)
df_2020 = pd.read_csv("../data/afl_results_2020.csv")
#print(df_2020.shape)
df_2021 = pd.read_csv("../data/afl_results_2021.csv")
#print(df_2021.shape)
df_2022 = pd.read_csv("../data/afl_results_2022.csv")
df_all = pd.concat([df_2017, df_2018, df_2019, df_2020, df_2021,df_2022], axis=0)

In [3]:
df_all.tail()

,match.name,match.date,match.status,match.matchId,match.venue,match.utcStartTime,match.homeTeamId,match.awayTeamId,match.round,match.venueLocalStartTime,...,homeTeamScoreChart.rushedBehinds,homeTeamScoreChart.touchedBehinds,awayTeamScoreChart.goals,awayTeamScoreChart.leftBehinds,awayTeamScoreChart.rightBehinds,awayTeamScoreChart.leftPosters,awayTeamScoreChart.rightPosters,awayTeamScoreChart.rushedBehinds,awayTeamScoreChart.touchedBehinds,venue.landOwner
127,Carlton Vs St Kilda,2022-07-01 09:50:00,CONCLUDED,CD_M20220141603,CD_V190,2022-07-01T09:50:00,CD_T30,CD_T130,CD_R202201416,2022-07-01T19:50:00,...,5,0,14,2,4,2,0,1,0,Wurundjeri people of the Kulin Nation
128,Essendon Vs Sydney Swans,2022-07-02 03:45:00,CONCLUDED,CD_M20220141604,CD_V40,2022-07-02T03:45:00,CD_T50,CD_T160,CD_R202201416,2022-07-02T13:45:00,...,2,0,12,8,2,2,0,2,0,Wurundjeri people of the Kulin Nation
129,Adelaide Crows Vs Melbourne,2022-07-02 06:35:00,CONCLUDED,CD_M20220141601,CD_V6,2022-07-02T06:35:00,CD_T10,CD_T90,CD_R202201416,2022-07-02T16:05:00,...,1,0,14,4,1,1,1,3,0,NaN
130,Geelong Cats Vs North Melbourne,2022-07-02 09:25:00,CONCLUDED,CD_M20220141606,CD_V30,2022-07-02T09:25:00,CD_T70,CD_T100,CD_R202201416,2022-07-02T19:25:00,...,6,1,5,0,1,1,0,0,0,Wadawurrung People
131,Gold Coast Suns Vs Collingwood,2022-07-02 09:25:00,CONCLUDED,CD_M20220141607,CD_V81,2022-07-02T09:25:00,CD_T1000,CD_T40,CD_R202201416,2022-07-02T19:25:00,...,7,0,9,4,2,0,3,4,0,NaN

In [4]:
df_all.columns

Index(['match.name', 'match.date', 'match.status', 'match.matchId',
       'match.venue', 'match.utcStartTime', 'match.homeTeamId',
       'match.awayTeamId', 'match.round', 'match.venueLocalStartTime',
       'match.abbr', 'match.twitterHashTag', 'match.homeTeam.name',
       'match.homeTeam.timeZone', 'match.homeTeam.teamId',
       'match.homeTeam.abbr', 'match.homeTeam.nickname', 'match.awayTeam.name',
       'match.awayTeam.timeZone', 'match.awayTeam.teamId',
       'match.awayTeam.abbr', 'match.awayTeam.nickname', 'venue.address',
       'venue.name', 'venue.state', 'venue.timeZone', 'venue.venueId',
       'venue.abbreviation', 'venue.capacity', 'venue.groundDimension',
       'venue.latitude', 'venue.longitude', 'round.name', 'round.year',
       'round.roundId', 'round.abbreviation', 'round.competitionId',
       'round.roundNumber', 'status', 'matchId', 'scoreWorm', 'scoreMap',
       'lastUpdated', 'homeTeamScore.periodScore',
       'homeTeamScore.rushedBehinds', 'homeTeamScore.minutesInFront',
       'homeTeamScore.matchScore.totalScore', 'homeTeamScore.matchScore.goals',
       'homeTeamScore.matchScore.behinds',
       'homeTeamScore.matchScore.superGoals', 'awayTeamScore.periodScore',
       'awayTeamScore.rushedBehinds', 'awayTeamScore.minutesInFront',
       'awayTeamScore.matchScore.totalScore', 'awayTeamScore.matchScore.goals',
       'awayTeamScore.matchScore.behinds',
       'awayTeamScore.matchScore.superGoals', 'matchClock.periods',
       'weather.description', 'weather.tempInCelsius', 'weather.weatherType',
       'homeTeamScoreChart.goals', 'homeTeamScoreChart.leftBehinds',
       'homeTeamScoreChart.rightBehinds', 'homeTeamScoreChart.leftPosters',
       'homeTeamScoreChart.rightPosters', 'homeTeamScoreChart.rushedBehinds',
       'homeTeamScoreChart.touchedBehinds', 'awayTeamScoreChart.goals',
       'awayTeamScoreChart.leftBehinds', 'awayTeamScoreChart.rightBehinds',
       'awayTeamScoreChart.leftPosters', 'awayTeamScoreChart.rightPosters',
       'awayTeamScoreChart.rushedBehinds', 'awayTeamScoreChart.touchedBehinds',
       'venue.landOwner'],
      dtype='object')

In [78]:
df_all[['venue.name','homeTeamScore.matchScore.totalScore','homeTeamScore.periodScore']]

,venue.name,homeTeamScore.matchScore.totalScore,homeTeamScore.periodScore
0,MCG,89,"1, 2, 3, 4, 27, 19, 30, 13, 4, 3, 5, 2, 3, 1, ..."
1,MCG,86,"1, 2, 3, 4, 27, 19, 30, 13, 4, 3, 5, 2, 3, 1, ..."
2,Marvel Stadium,90,"1, 2, 3, 4, 27, 19, 30, 13, 4, 3, 5, 2, 3, 1, ..."
3,SCG,82,"1, 2, 3, 4, 27, 19, 30, 13, 4, 3, 5, 2, 3, 1, ..."
4,MCG,116,"1, 2, 3, 4, 27, 19, 30, 13, 4, 3, 5, 2, 3, 1, ..."
...,...,...,...
127,Marvel Stadium,78,"1, 2, 3, 4, 29, 13, 26, 29, 4, 2, 4, 4, 5, 1, ..."
128,MCG,95,"1, 2, 3, 4, 29, 13, 26, 29, 4, 2, 4, 4, 5, 1, ..."
129,Adelaide Oval,65,"1, 2, 3, 4, 29, 13, 26, 29, 4, 2, 4, 4, 5, 1, ..."
130,GMHBA Stadium,144,"1, 2, 3, 4, 29, 13, 26, 29, 4, 2, 4, 4, 5, 1, ..."
131,Metricon Stadium,62,"1, 2, 3, 4, 29, 13, 26, 29, 4, 2, 4, 4, 5, 1, ..."

In [96]:
df_1 = df_all[['match.date','match.homeTeam.name','match.awayTeam.name','round.roundNumber','round.year','venue.name',
        'homeTeamScore.rushedBehinds', 
        'homeTeamScore.minutesInFront',
       'homeTeamScore.matchScore.totalScore', 
        'homeTeamScore.matchScore.goals',
       'homeTeamScore.matchScore.behinds',
        'homeTeamScoreChart.leftBehinds',
       'homeTeamScoreChart.rightBehinds', 
        'homeTeamScoreChart.leftPosters',
       'homeTeamScoreChart.rightPosters', 
       'homeTeamScoreChart.touchedBehinds',        
       'awayTeamScore.rushedBehinds', 
        'awayTeamScore.minutesInFront',
       'awayTeamScore.matchScore.totalScore', 
        'awayTeamScore.matchScore.goals',
       'awayTeamScore.matchScore.behinds',
       'awayTeamScoreChart.leftBehinds', 
       'awayTeamScoreChart.rightBehinds',
       'awayTeamScoreChart.leftPosters', 
       'awayTeamScoreChart.rightPosters',
        'awayTeamScoreChart.touchedBehinds'
]]

df_1['game'] = np.arange(len(df_1))
df_1['home_game'] = 1

df_1 = df_1.rename(columns={'match.date':'date',
                            'venue.name':'venue',
                            
                            'round.roundNumber':'round',
                            'round.year':'season',
                            
                            'match.homeTeam.name': 'team', 
                            'match.awayTeam.name': 'opponent',
                           'homeTeamScore.rushedBehinds': 'RushB', 
                           'homeTeamScore.minutesInFront': 'MIF',
                           'homeTeamScore.matchScore.totalScore': 'S', 
                            'homeTeamScore.matchScore.goals': 'G',
                           'homeTeamScore.matchScore.behinds': 'B', 
                            'homeTeamScoreChart.leftBehinds': 'LB',
                           'homeTeamScoreChart.rightBehinds': 'RightB', 
                            'homeTeamScoreChart.leftPosters': 'LP',
                           'homeTeamScoreChart.rightPosters': 'RP', 
                           'homeTeamScoreChart.touchedBehinds': 'TB',        
                           'awayTeamScore.rushedBehinds': 'opp_RushB', 
                            'awayTeamScore.minutesInFront': 'opp_MIF',
                           'awayTeamScore.matchScore.totalScore': 'opp_S', 
                            'awayTeamScore.matchScore.goals': 'opp_G',
                           'awayTeamScore.matchScore.behinds': 'opp_B',
                           'awayTeamScoreChart.leftBehinds': 'opp_LB', 
                           'awayTeamScoreChart.rightBehinds': 'opp_RightB',
                           'awayTeamScoreChart.leftPosters': 'opp_LP', 
                           'awayTeamScoreChart.rightPosters': 'opp_RP',
                            'awayTeamScoreChart.touchedBehinds': 'opp_TB'
                           })

df_1

C:\Users\Damian Joseph\AppData\Local\Temp\ipykernel_50628\2717988598.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1['game'] = np.arange(len(df_1))
C:\Users\Damian Joseph\AppData\Local\Temp\ipykernel_50628\2717988598.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_1['home_game'] = 1

,date,team,opponent,round,season,venue,RushB,MIF,S,G,...,opp_S,opp_G,opp_B,opp_LB,opp_RightB,opp_LP,opp_RP,opp_TB,game,home_game
0,2017-03-23 08:20:00,Carlton,Richmond,1,2017,MCG,1,0,89,14,...,132,20,12,5,3,0,1,0,0,1
1,2017-03-24 08:50:00,Collingwood,Western Bulldogs,1,2017,MCG,3,4,86,12,...,100,15,10,3,2,0,1,0,1,1
2,2017-03-25 05:35:00,St Kilda,Melbourne,1,2017,Marvel Stadium,2,32,90,13,...,120,18,12,4,5,0,1,0,2,1
3,2017-03-25 05:35:00,Sydney Swans,Port Adelaide,1,2017,SCG,1,32,82,12,...,110,17,8,1,6,0,0,1,3,1
4,2017-03-25 08:25:00,Essendon,Hawthorn,1,2017,MCG,2,85,116,17,...,91,12,19,5,9,0,0,0,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,2022-07-01 09:50:00,Carlton,St Kilda,16,2022,Marvel Stadium,5,17,78,10,...,93,14,9,2,4,2,0,0,1117,1
128,2022-07-02 03:45:00,Essendon,Sydney Swans,16,2022,MCG,2,37,95,15,...,86,12,14,8,2,2,0,0,1118,1
129,2022-07-02 06:35:00,Adelaide Crows,Melbourne,16,2022,Adelaide Oval,1,4,65,10,...,94,14,10,4,1,1,1,0,1119,1
130,2022-07-02 09:25:00,Geelong Cats,North Melbourne,16,2022,GMHBA Stadium,6,120,144,21,...,32,5,2,0,1,1,0,0,1120,1
131,2022-07-02 09:25:00,Gold Coast Suns,Collingwood,16,2022,Metricon Stadium,7,42,62,8,...,67,9,13,4,2,0,3,0,1121,1

In [97]:
df_2 = df_1.rename(columns={'team':'opponent', 
                            'opponent':'team',
                            'RushB':'opp_RushB', 
                            'MIF':'opp_MIF',
                            'S':'opp_S', 
                            'G':'opp_G',
                            'B':'opp_B', 
                            'LB':'opp_LB',
                            'RightB':'opp_RightB', 
                            'LP':'opp_LP',
                            'RP':'opp_RP', 
                            'TB':'opp_TB',        
                            'opp_RushB':'RushB', 
                            'opp_MIF':'MIF',
                            'opp_S':'S', 
                            'opp_G':'G',
                            'opp_B':'B',
                            'opp_LB':'LB', 
                            'opp_RightB':'RightB',
                            'opp_LP':'LP', 
                            'opp_RP':'RP',
                            'opp_TB':'TB'}).copy()
df_2['home_game'] = 0
df_2

,date,opponent,team,round,season,venue,opp_RushB,opp_MIF,opp_S,opp_G,...,S,G,B,LB,RightB,LP,RP,TB,game,home_game
0,2017-03-23 08:20:00,Carlton,Richmond,1,2017,MCG,1,0,89,14,...,132,20,12,5,3,0,1,0,0,0
1,2017-03-24 08:50:00,Collingwood,Western Bulldogs,1,2017,MCG,3,4,86,12,...,100,15,10,3,2,0,1,0,1,0
2,2017-03-25 05:35:00,St Kilda,Melbourne,1,2017,Marvel Stadium,2,32,90,13,...,120,18,12,4,5,0,1,0,2,0
3,2017-03-25 05:35:00,Sydney Swans,Port Adelaide,1,2017,SCG,1,32,82,12,...,110,17,8,1,6,0,0,1,3,0
4,2017-03-25 08:25:00,Essendon,Hawthorn,1,2017,MCG,2,85,116,17,...,91,12,19,5,9,0,0,0,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,2022-07-01 09:50:00,Carlton,St Kilda,16,2022,Marvel Stadium,5,17,78,10,...,93,14,9,2,4,2,0,0,1117,0
128,2022-07-02 03:45:00,Essendon,Sydney Swans,16,2022,MCG,2,37,95,15,...,86,12,14,8,2,2,0,0,1118,0
129,2022-07-02 06:35:00,Adelaide Crows,Melbourne,16,2022,Adelaide Oval,1,4,65,10,...,94,14,10,4,1,1,1,0,1119,0
130,2022-07-02 09:25:00,Geelong Cats,North Melbourne,16,2022,GMHBA Stadium,6,120,144,21,...,32,5,2,0,1,1,0,0,1120,0
131,2022-07-02 09:25:00,Gold Coast Suns,Collingwood,16,2022,Metricon Stadium,7,42,62,8,...,67,9,13,4,2,0,3,0,1121,0

In [98]:
df_1.columns

Index(['date', 'team', 'opponent', 'round', 'season', 'venue', 'RushB', 'MIF',
       'S', 'G', 'B', 'LB', 'RightB', 'LP', 'RP', 'TB', 'opp_RushB', 'opp_MIF',
       'opp_S', 'opp_G', 'opp_B', 'opp_LB', 'opp_RightB', 'opp_LP', 'opp_RP',
       'opp_TB', 'game', 'home_game'],
      dtype='object')

In [99]:
df_2.columns

Index(['date', 'opponent', 'team', 'round', 'season', 'venue', 'opp_RushB',
       'opp_MIF', 'opp_S', 'opp_G', 'opp_B', 'opp_LB', 'opp_RightB', 'opp_LP',
       'opp_RP', 'opp_TB', 'RushB', 'MIF', 'S', 'G', 'B', 'LB', 'RightB', 'LP',
       'RP', 'TB', 'game', 'home_game'],
      dtype='object')

In [100]:
print (df_2.columns[df_2.columns.duplicated(keep=False)])

Index([], dtype='object')

In [101]:
afl_data = pd.concat([df_1,df_2], ignore_index=True)

In [103]:
afl_data = afl_data.sort_values(by=['date','game'], ascending=True).reset_index(drop=True)
afl_data

,date,team,opponent,round,season,venue,RushB,MIF,S,G,...,opp_S,opp_G,opp_B,opp_LB,opp_RightB,opp_LP,opp_RP,opp_TB,game,home_game
0,2017-03-23 08:20:00,Carlton,Richmond,1,2017,MCG,1,0,89,14,...,132,20,12,5,3,0,1,0,0,1
1,2017-03-23 08:20:00,Richmond,Carlton,1,2017,MCG,3,116,132,20,...,89,14,5,1,2,1,0,0,0,0
2,2017-03-24 08:50:00,Collingwood,Western Bulldogs,1,2017,MCG,3,4,86,12,...,100,15,10,3,2,0,1,0,1,1
3,2017-03-24 08:50:00,Western Bulldogs,Collingwood,1,2017,MCG,4,98,100,15,...,86,12,14,6,4,0,1,0,1,0
4,2017-03-25 05:35:00,St Kilda,Melbourne,1,2017,Marvel Stadium,2,32,90,13,...,120,18,12,4,5,0,1,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2239,2022-07-02 06:35:00,Melbourne,Adelaide Crows,16,2022,Adelaide Oval,3,92,94,14,...,65,10,5,1,3,0,0,0,1119,0
2240,2022-07-02 09:25:00,Geelong Cats,North Melbourne,16,2022,GMHBA Stadium,6,120,144,21,...,32,5,2,0,1,1,0,0,1120,1
2241,2022-07-02 09:25:00,North Melbourne,Geelong Cats,16,2022,GMHBA Stadium,0,0,32,5,...,144,21,18,5,6,0,0,1,1120,0
2242,2022-07-02 09:25:00,Gold Coast Suns,Collingwood,16,2022,Metricon Stadium,7,42,62,8,...,67,9,13,4,2,0,3,0,1121,1
2243,2022-07-02 09:25:00,Collingwood,Gold Coast Suns,16,2022,Metricon Stadium,4,54,67,9,...,62,8,14,2,4,1,0,0,1121,0

In [104]:
non_feature_cols = ['team', 'date', 'home_game', 'game', 'round', 'venue', 'opponent', 'season']
afl_data = afl_data.rename(columns={col: 'f_' + col for col in afl_data if col not in non_feature_cols})

In [105]:
features = afl_data[['date', 'game', 'team', 'opponent', 'venue', 'home_game']].copy()

In [106]:
# Define a function which returns a DataFrame with the expontential moving average for each numeric stat
def create_exp_weighted_avgs(df, span):
    # Create a copy of the df with only the game id and the team - we will add cols to this df
    ema_features = df[['game', 'team']].copy()

    feature_names = [col for col in df.columns if col.startswith('f_')] # Get a list of columns we will iterate over

    for feature_name in feature_names:
        feature_ema = (df.groupby('team')[feature_name]
                         .transform(lambda row: (row.ewm(span=span)
                                                    .mean()
                                                    .shift(1))))
        ema_features[feature_name] = feature_ema

    return ema_features

In [107]:
features_rolling_averages = create_exp_weighted_avgs(afl_data, span=10)

In [108]:
features_rolling_averages.tail()

,game,team,f_RushB,f_MIF,f_S,f_G,f_B,f_LB,f_RightB,f_LP,...,f_opp_RushB,f_opp_MIF,f_opp_S,f_opp_G,f_opp_B,f_opp_LB,f_opp_RightB,f_opp_LP,f_opp_RP,f_opp_TB
2239,1119,Melbourne,3.484838,84.342686,86.156440,12.149724,13.258098,5.101868,2.940233,0.667345,...,1.702665,24.482306,65.166922,9.239559,9.729568,3.789632,2.793660,0.441176,0.536005,0.466429
2240,1120,Geelong Cats,2.756467,88.395485,86.025474,12.422985,11.487563,4.269001,3.375045,0.325340,...,1.777120,22.658453,69.825242,10.118687,9.113121,2.733518,2.917512,0.847221,0.556685,0.281066
2241,1120,North Melbourne,2.403232,11.381180,53.866049,7.665736,7.871633,1.921273,2.468078,0.361338,...,2.956247,102.200325,107.083617,15.627728,13.317249,5.066872,3.376458,0.544904,0.849817,0.522952
2242,1121,Gold Coast Suns,2.195888,56.571212,92.984953,13.546129,11.708178,4.946057,3.107637,0.574735,...,2.713197,59.187207,77.019083,10.886001,11.703080,3.417589,4.498001,0.258913,0.466795,0.348585
2243,1121,Collingwood,2.930777,62.632773,81.520740,11.484671,12.612713,4.100289,3.531859,1.076155,...,1.955035,44.850546,76.197288,11.332718,8.200983,2.748008,2.886723,0.184920,0.319801,0.106497

In [109]:
features = pd.merge(features, features_rolling_averages, on=['game', 'team'])

In [110]:
features_rolling_averages.team.unique()

array(['Carlton', 'Richmond', 'Collingwood', 'Western Bulldogs',
       'St Kilda', 'Melbourne', 'Sydney Swans', 'Port Adelaide',
       'Essendon', 'Hawthorn', 'Gold Coast Suns', 'Brisbane Lions',
       'North Melbourne', 'West Coast Eagles', 'Adelaide Crows',
       'GWS Giants', 'Fremantle', 'Geelong Cats'], dtype=object)

In [67]:
df_2.shape

(1122, 27)

In [68]:
afl_data.shape

(2244, 27)