In [179]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

## Load match related data

In [180]:

#df_2014 = pd.read_csv("../data/afl_results_2014.csv")
#print(df_2014.shape)

#df_2015 = pd.read_csv("../data/afl_results_2015.csv")
#print(df_2015.shape)

#df_2016 = pd.read_csv("../data/afl_results_2016.csv")
#print(df_2016.shape)

df_2017 = pd.read_csv("../data/afl_results_2017.csv")
print(df_2017.shape)

df_2018 = pd.read_csv("../data/afl_results_2018.csv")
print(df_2018.shape)

df_2019 = pd.read_csv("../data/afl_results_2019.csv")
print(df_2019.shape)
df_2020 = pd.read_csv("../data/afl_results_2020.csv")
print(df_2020.shape)
df_2021 = pd.read_csv("../data/afl_results_2021.csv")
print(df_2021.shape)
#df_2022 = pd.read_csv("../data/afl_results_2022.csv")
#print(df_2022.shape)

df_all = pd.concat([df_2017, df_2018, df_2019, df_2020, df_2021], axis=0)
print(df_all.shape)
df_all.columns

(207, 75)
(207, 75)
(207, 75)
(162, 75)
(207, 75)
(990, 75)

Index(['match.name', 'match.date', 'match.status', 'match.matchId',
       'match.venue', 'match.utcStartTime', 'match.homeTeamId',
       'match.awayTeamId', 'match.round', 'match.venueLocalStartTime',
       'match.abbr', 'match.twitterHashTag', 'match.homeTeam.name',
       'match.homeTeam.timeZone', 'match.homeTeam.teamId',
       'match.homeTeam.abbr', 'match.homeTeam.nickname', 'match.awayTeam.name',
       'match.awayTeam.timeZone', 'match.awayTeam.teamId',
       'match.awayTeam.abbr', 'match.awayTeam.nickname', 'venue.address',
       'venue.name', 'venue.state', 'venue.timeZone', 'venue.venueId',
       'venue.abbreviation', 'venue.capacity', 'venue.groundDimension',
       'venue.latitude', 'venue.longitude', 'round.name', 'round.year',
       'round.roundId', 'round.abbreviation', 'round.competitionId',
       'round.roundNumber', 'status', 'matchId', 'scoreWorm', 'scoreMap',
       'lastUpdated', 'homeTeamScore.periodScore',
       'homeTeamScore.rushedBehinds', 'homeTeamScore.minutesInFront',
       'homeTeamScore.matchScore.totalScore', 'homeTeamScore.matchScore.goals',
       'homeTeamScore.matchScore.behinds',
       'homeTeamScore.matchScore.superGoals', 'awayTeamScore.periodScore',
       'awayTeamScore.rushedBehinds', 'awayTeamScore.minutesInFront',
       'awayTeamScore.matchScore.totalScore', 'awayTeamScore.matchScore.goals',
       'awayTeamScore.matchScore.behinds',
       'awayTeamScore.matchScore.superGoals', 'matchClock.periods',
       'weather.description', 'weather.tempInCelsius', 'weather.weatherType',
       'homeTeamScoreChart.goals', 'homeTeamScoreChart.leftBehinds',
       'homeTeamScoreChart.rightBehinds', 'homeTeamScoreChart.leftPosters',
       'homeTeamScoreChart.rightPosters', 'homeTeamScoreChart.rushedBehinds',
       'homeTeamScoreChart.touchedBehinds', 'awayTeamScoreChart.goals',
       'awayTeamScoreChart.leftBehinds', 'awayTeamScoreChart.rightBehinds',
       'awayTeamScoreChart.leftPosters', 'awayTeamScoreChart.rightPosters',
       'awayTeamScoreChart.rushedBehinds',
       'awayTeamScoreChart.touchedBehinds'],
      dtype='object')

In [226]:
df_all.dtypes

match.name                           object
match.date                           object
match.status                         object
match.matchId                        object
match.venue                          object
                                      ...
awayTeamScoreChart.leftPosters        int64
awayTeamScoreChart.rightPosters       int64
awayTeamScoreChart.rushedBehinds      int64
awayTeamScoreChart.touchedBehinds     int64
Date                                 object
Length: 76, dtype: object

In [227]:
df_all[['matchId']]

             matchId
0    CD_M20170140101
1    CD_M20170140102
2    CD_M20170140103
3    CD_M20170140104
4    CD_M20170140106
..               ...
985  CD_M20210142501
986  CD_M20210142502
987  CD_M20210142601
988  CD_M20210142602
989  CD_M20210142701

[990 rows x 1 columns]

In [182]:
df_all.head()

,match.name,match.date,match.status,match.matchId,match.venue,match.utcStartTime,match.homeTeamId,match.awayTeamId,match.round,match.venueLocalStartTime,...,homeTeamScoreChart.rightPosters,homeTeamScoreChart.rushedBehinds,homeTeamScoreChart.touchedBehinds,awayTeamScoreChart.goals,awayTeamScoreChart.leftBehinds,awayTeamScoreChart.rightBehinds,awayTeamScoreChart.leftPosters,awayTeamScoreChart.rightPosters,awayTeamScoreChart.rushedBehinds,awayTeamScoreChart.touchedBehinds
0,Carlton Vs Richmond,2017-03-23 08:20:00,CONCLUDED,CD_M20170140101,CD_V40,2017-03-23T08:20:00,CD_T30,CD_T120,CD_R201701401,2017-03-23T19:20:00,...,0,1,0,20,5,3,0,1,3,0
1,Collingwood Vs Western Bulldogs,2017-03-24 08:50:00,CONCLUDED,CD_M20170140102,CD_V40,2017-03-24T08:50:00,CD_T40,CD_T140,CD_R201701401,2017-03-24T19:50:00,...,1,3,0,15,3,2,0,1,4,0
2,St Kilda Vs Melbourne,2017-03-25 05:35:00,CONCLUDED,CD_M20170140103,CD_V190,2017-03-25T05:35:00,CD_T130,CD_T90,CD_R201701401,2017-03-25T16:35:00,...,0,2,0,18,4,5,0,1,2,0
3,Sydney Swans Vs Port Adelaide,2017-03-25 05:35:00,CONCLUDED,CD_M20170140104,CD_V60,2017-03-25T05:35:00,CD_T160,CD_T110,CD_R201701401,2017-03-25T16:35:00,...,0,1,0,17,1,6,0,0,0,1
4,Essendon Vs Hawthorn,2017-03-25 08:25:00,CONCLUDED,CD_M20170140106,CD_V40,2017-03-25T08:25:00,CD_T50,CD_T80,CD_R201701401,2017-03-25T19:25:00,...,0,2,0,12,5,9,0,0,5,0

In [183]:

df_all['Date'] = pd.to_datetime(df_all['match.date']).dt.strftime("%Y-%m-%d")
df_all[['Date','match.date']].head()

         Date           match.date
0  2017-03-23  2017-03-23 08:20:00
1  2017-03-24  2017-03-24 08:50:00
2  2017-03-25  2017-03-25 05:35:00
3  2017-03-25  2017-03-25 05:35:00
4  2017-03-25  2017-03-25 08:25:00

In [184]:
# Read player data

df_players_2017 = pd.read_csv("../data/afl_players_stats_2017.csv")
print(df_players_2017.shape)
df_players_2018 = pd.read_csv("../data/afl_players_stats_2018.csv")
print(df_players_2018.shape)
df_players_2019 = pd.read_csv("../data/afl_players_stats_2019.csv")
print(df_players_2019.shape)
df_players_2020 = pd.read_csv("../data/afl_players_stats_2020.csv")
print(df_players_2020.shape)
df_players_2021 = pd.read_csv("../data/afl_players_stats_2021.csv")
print(df_players_2021.shape)
df_players_2022 = pd.read_csv("../data/afl_players_stats_2022.csv")
print(df_players_2022.shape)

df_players = pd.concat([df_players_2017, df_players_2018, df_players_2019,df_players_2020,df_players_2021], axis=0)
print(df_players.shape)
df_players.columns

(9108, 59)
(9108, 59)
(9108, 59)
(7128, 59)
(9526, 59)
(3726, 59)
(43978, 59)

Index(['Season', 'Round', 'Date', 'Local.start.time', 'Venue', 'Attendance',
       'Home.team', 'HQ1G', 'HQ1B', 'HQ2G', 'HQ2B', 'HQ3G', 'HQ3B', 'HQ4G',
       'HQ4B', 'Home.score', 'Away.team', 'AQ1G', 'AQ1B', 'AQ2G', 'AQ2B',
       'AQ3G', 'AQ3B', 'AQ4G', 'AQ4B', 'Away.score', 'First.name', 'Surname',
       'ID', 'Jumper.No.', 'Playing.for', 'Kicks', 'Marks', 'Handballs',
       'Goals', 'Behinds', 'Hit.Outs', 'Tackles', 'Rebounds', 'Inside.50s',
       'Clearances', 'Clangers', 'Frees.For', 'Frees.Against',
       'Brownlow.Votes', 'Contested.Possessions', 'Uncontested.Possessions',
       'Contested.Marks', 'Marks.Inside.50', 'One.Percenters', 'Bounces',
       'Goal.Assists', 'Time.on.Ground..', 'Substitute', 'Umpire.1',
       'Umpire.2', 'Umpire.3', 'Umpire.4', 'group_id'],
      dtype='object')

In [185]:
df_players.head()

,Season,Round,Date,Local.start.time,Venue,Attendance,Home.team,HQ1G,HQ1B,HQ2G,...,One.Percenters,Bounces,Goal.Assists,Time.on.Ground..,Substitute,Umpire.1,Umpire.2,Umpire.3,Umpire.4,group_id
0,2017,1,2017-03-23,1920,M.C.G.,73137,Carlton,4,3,7,...,0,0,0,82,NaN,Sam Hay,Mathew Nicholls,Matt Stevic,NaN,NaN
1,2017,1,2017-03-23,1920,M.C.G.,73137,Carlton,4,3,7,...,1,0,0,81,NaN,Sam Hay,Mathew Nicholls,Matt Stevic,NaN,NaN
2,2017,1,2017-03-23,1920,M.C.G.,73137,Carlton,4,3,7,...,0,0,0,84,NaN,Sam Hay,Mathew Nicholls,Matt Stevic,NaN,NaN
3,2017,1,2017-03-23,1920,M.C.G.,73137,Carlton,4,3,7,...,1,0,0,76,NaN,Sam Hay,Mathew Nicholls,Matt Stevic,NaN,NaN
4,2017,1,2017-03-23,1920,M.C.G.,73137,Carlton,4,3,7,...,0,2,0,86,NaN,Sam Hay,Mathew Nicholls,Matt Stevic,NaN,NaN

In [186]:
def get_aggregate_player_stats(df=None):

    agg_stats = (df.rename(columns={ # Rename columns to lowercase
                    'Home.team': 'match.homeTeam.name',
                    'Away.team': 'match.awayTeam.name'
                    })
                   .groupby(by=['Date', 'Season', 'match.homeTeam.name', 'match.awayTeam.name'], as_index=False) # Groupby to aggregate the stats for each game
                   .sum()
                   #.drop(columns=['DE', 'TOG', 'Match_id']) # Drop columns
                   .assign(date=lambda df: pd.to_datetime(df.Date, format="%Y-%m-%d")) # Create a datetime object
                   .sort_values(by='Date')
                   .reset_index(drop=True))
    return agg_stats

In [187]:
agg_player = get_aggregate_player_stats(df_players)
print(agg_player.shape)
print(agg_player.columns)

(990, 50)
Index(['Date', 'Season', 'match.homeTeam.name', 'match.awayTeam.name',
       'Local.start.time', 'Attendance', 'HQ1G', 'HQ1B', 'HQ2G', 'HQ2B',
       'HQ3G', 'HQ3B', 'HQ4G', 'HQ4B', 'Home.score', 'AQ1G', 'AQ1B', 'AQ2G',
       'AQ2B', 'AQ3G', 'AQ3B', 'AQ4G', 'AQ4B', 'Away.score', 'ID', 'Kicks',
       'Marks', 'Handballs', 'Goals', 'Behinds', 'Hit.Outs', 'Tackles',
       'Rebounds', 'Inside.50s', 'Clearances', 'Clangers', 'Frees.For',
       'Frees.Against', 'Brownlow.Votes', 'Contested.Possessions',
       'Uncontested.Possessions', 'Contested.Marks', 'Marks.Inside.50',
       'One.Percenters', 'Bounces', 'Goal.Assists', 'Time.on.Ground..',
       'Substitute', 'group_id', 'date'],
      dtype='object')

In [188]:
print(df_all.shape)
print(agg_player.shape)

#df_all[['Date', 'match.homeTeam.name', 'match.awayTeam.name']]
#agg_player[['Date', 'match.homeTeam.name', 'match.awayTeam.name']]

(990, 76)
(990, 50)

In [189]:
afl_df = df_all.merge(agg_player, on=['Date', 'match.homeTeam.name', 'match.awayTeam.name'], how='left')

In [190]:
afl_df.shape

(990, 123)

In [191]:
print(afl_df.columns.tolist())

['match.name', 'match.date', 'match.status', 'match.matchId', 'match.venue', 'match.utcStartTime', 'match.homeTeamId', 'match.awayTeamId', 'match.round', 'match.venueLocalStartTime', 'match.abbr', 'match.twitterHashTag', 'match.homeTeam.name', 'match.homeTeam.timeZone', 'match.homeTeam.teamId', 'match.homeTeam.abbr', 'match.homeTeam.nickname', 'match.awayTeam.name', 'match.awayTeam.timeZone', 'match.awayTeam.teamId', 'match.awayTeam.abbr', 'match.awayTeam.nickname', 'venue.address', 'venue.name', 'venue.state', 'venue.timeZone', 'venue.venueId', 'venue.abbreviation', 'venue.capacity', 'venue.groundDimension', 'venue.latitude', 'venue.longitude', 'round.name', 'round.year', 'round.roundId', 'round.abbreviation', 'round.competitionId', 'round.roundNumber', 'status', 'matchId', 'scoreWorm', 'scoreMap', 'lastUpdated', 'homeTeamScore.periodScore', 'homeTeamScore.rushedBehinds', 'homeTeamScore.minutesInFront', 'homeTeamScore.matchScore.totalScore', 'homeTeamScore.matchScore.goals', 'homeTeamScore.matchScore.behinds', 'homeTeamScore.matchScore.superGoals', 'awayTeamScore.periodScore', 'awayTeamScore.rushedBehinds', 'awayTeamScore.minutesInFront', 'awayTeamScore.matchScore.totalScore', 'awayTeamScore.matchScore.goals', 'awayTeamScore.matchScore.behinds', 'awayTeamScore.matchScore.superGoals', 'matchClock.periods', 'weather.description', 'weather.tempInCelsius', 'weather.weatherType', 'homeTeamScoreChart.goals', 'homeTeamScoreChart.leftBehinds', 'homeTeamScoreChart.rightBehinds', 'homeTeamScoreChart.leftPosters', 'homeTeamScoreChart.rightPosters', 'homeTeamScoreChart.rushedBehinds', 'homeTeamScoreChart.touchedBehinds', 'awayTeamScoreChart.goals', 'awayTeamScoreChart.leftBehinds', 'awayTeamScoreChart.rightBehinds', 'awayTeamScoreChart.leftPosters', 'awayTeamScoreChart.rightPosters', 'awayTeamScoreChart.rushedBehinds', 'awayTeamScoreChart.touchedBehinds', 'Date', 'Season', 'Local.start.time', 'Attendance', 'HQ1G', 'HQ1B', 'HQ2G', 'HQ2B', 'HQ3G', 'HQ3B', 'HQ4G', 'HQ4B', 'Home.score', 'AQ1G', 'AQ1B', 'AQ2G', 'AQ2B', 'AQ3G', 'AQ3B', 'AQ4G', 'AQ4B', 'Away.score', 'ID', 'Kicks', 'Marks', 'Handballs', 'Goals', 'Behinds', 'Hit.Outs', 'Tackles', 'Rebounds', 'Inside.50s', 'Clearances', 'Clangers', 'Frees.For', 'Frees.Against', 'Brownlow.Votes', 'Contested.Possessions', 'Uncontested.Possessions', 'Contested.Marks', 'Marks.Inside.50', 'One.Percenters', 'Bounces', 'Goal.Assists', 'Time.on.Ground..', 'Substitute', 'group_id', 'date']

In [192]:
df_fixture = pd.read_csv("../data/fixture_2022.csv")
print(df_fixture.shape)
df_fixture.columns

df_next_games_teams = df_fixture[(df_fixture['status'] != "CONCLUDED") & (df_fixture['round.roundNumber'] == 11)]
df_next_games_teams = df_next_games_teams[['home.team.name','away.team.name']]
df_next_games_teams = df_next_games_teams.rename(columns={'home.team.name': 'match.homeTeam.name', 'away.team.name': 'match.awayTeam.name'})
df_next_games_teams

(198, 54)

   match.homeTeam.name match.awayTeam.name
90        Sydney Swans            Richmond
91      Brisbane Lions          GWS Giants
92        Geelong Cats      Adelaide Crows
93           Melbourne           Fremantle
94   West Coast Eagles    Western Bulldogs
95     Gold Coast Suns            Hawthorn
96            St Kilda     North Melbourne
97         Collingwood             Carlton
98       Port Adelaide            Essendon

In [193]:

df_fixture.columns
print(df_fixture.columns.tolist())

['id', 'providerId', 'utcStartTime', 'status', 'compSeason.id', 'compSeason.providerId', 'compSeason.name', 'compSeason.shortName', 'compSeason.currentRoundNumber', 'round.id', 'round.providerId', 'round.abbreviation', 'round.name', 'round.roundNumber', 'round.byes', 'home.team.id', 'home.team.providerId', 'home.team.name', 'home.team.abbreviation', 'home.team.nickname', 'home.team.teamType', 'home.team.club.id', 'home.team.club.providerId', 'home.team.club.name', 'home.team.club.abbreviation', 'home.team.club.nickname', 'home.score.goals', 'home.score.behinds', 'home.score.totalScore', 'home.score.superGoals', 'away.team.id', 'away.team.providerId', 'away.team.name', 'away.team.abbreviation', 'away.team.nickname', 'away.team.teamType', 'away.team.club.id', 'away.team.club.providerId', 'away.team.club.name', 'away.team.club.abbreviation', 'away.team.club.nickname', 'away.score.goals', 'away.score.behinds', 'away.score.totalScore', 'away.score.superGoals', 'venue.id', 'venue.providerId', 'venue.name', 'venue.abbreviation', 'venue.location', 'venue.state', 'venue.timezone', 'metadata.ticket_link', 'compSeason.year']

In [194]:
df_all.shape

(990, 76)

In [195]:
df_all.sort_values('match.date', inplace=True)
df_all.reset_index(inplace=True)
df_all.drop('index', axis=1, inplace=True)

In [196]:
afl_df.tail()

,match.name,match.date,match.status,match.matchId,match.venue,match.utcStartTime,match.homeTeamId,match.awayTeamId,match.round,match.venueLocalStartTime,...,Uncontested.Possessions,Contested.Marks,Marks.Inside.50,One.Percenters,Bounces,Goal.Assists,Time.on.Ground..,Substitute,group_id,date
985,Geelong Cats Vs GWS Giants,2021-09-03 09:50:00,CONCLUDED,CD_M20210142501,CD_V2925,2021-09-03T09:50:00,CD_T70,CD_T1010,CD_R202101425,2021-09-03T17:50:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
986,Brisbane Lions Vs Western Bulldogs,2021-09-04 09:20:00,CONCLUDED,CD_M20210142502,CD_V20,2021-09-04T09:20:00,CD_T20,CD_T140,CD_R202101425,2021-09-04T19:20:00,...,396.0,15.0,18.0,136.0,13.0,17.0,3601.0,0.0,0.0,2021-09-04
987,Melbourne Vs Geelong Cats,2021-09-10 09:50:00,CONCLUDED,CD_M20210142601,CD_V2925,2021-09-10T09:50:00,CD_T90,CD_T70,CD_R202101426,2021-09-10T17:50:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT
988,Port Adelaide Vs Western Bulldogs,2021-09-11 09:40:00,CONCLUDED,CD_M20210142602,CD_V6,2021-09-11T09:40:00,CD_T110,CD_T140,CD_R202101426,2021-09-11T19:10:00,...,421.0,29.0,23.0,114.0,13.0,16.0,3599.0,0.0,0.0,2021-09-11
989,Melbourne Vs Western Bulldogs,2021-09-25 09:15:00,CONCLUDED,CD_M20210142701,CD_V2925,2021-09-25T09:15:00,CD_T90,CD_T140,CD_R202101427,2021-09-25T17:15:00,...,440.0,14.0,21.0,99.0,16.0,23.0,3601.0,0.0,0.0,2021-09-25

In [197]:
#from pandas.plotting import scatter_matrix

In [198]:
#scatter_matrix(df_all[df_all.iloc[:,50:56].columns], diagonal='kde', figsize=(14,14));

In [199]:
# HTGDIFF: Home Team Goal Difference
# ATGDIFF: Away Team Goal Difference

afl_df['HTGDIFF'] = afl_df['homeTeamScore.matchScore.goals'] - afl_df['awayTeamScore.matchScore.goals']
afl_df['ATGDIFF'] = afl_df['awayTeamScore.matchScore.goals'] - afl_df['homeTeamScore.matchScore.goals']

## Calculate AVG goal difference for home and away team rolling 4 Games

In [200]:
def avg_goal_diff(df, avg_h_a_diff, a_h_team, a_h_goal_letter):
    """
    input: 
        df = dataframe with all results
        avg_h_a_diff = name of the new column
        a_h_team = HomeTeam or AwayTeam
        a_h_goal_letter = 'H' for home or 'A' for away
    output: 
        avg_per_team = dictionary with with team as key and columns as values with new column H/ATGDIFF
    """
    df[avg_h_a_diff] = 0
    avg_per_team = {}
    all_teams = df[a_h_team].unique()
    for t in all_teams:
        df_team = df[df[a_h_team]==t].fillna(0)
        result = df_team['{}TGDIFF'.format(a_h_goal_letter)].rolling(4).mean()
        df_team[avg_h_a_diff] = result
        avg_per_team[t] = df_team
    return avg_per_team

In [201]:
d_AVGFTHG = avg_goal_diff(afl_df, 'AVGHTGDIFF', 'match.homeTeam.name', 'H')

In [202]:
def from_dict_value_to_df(d):
    """
    input = dictionary 
    output = dataframe as part of all the values from the dictionary
    """
    df = pd.DataFrame()
    for v in d.values():
        df = pd.concat([df,v])
    return df

In [203]:
df_AVGFTHG = from_dict_value_to_df(d_AVGFTHG)
df_AVGFTHG.sort_index(inplace=True)

In [204]:
d_AVGFTAG = avg_goal_diff(df_AVGFTHG, 'AVGATGDIFF', 'match.awayTeam.name', 'A')
afl_df = from_dict_value_to_df(d_AVGFTAG)
afl_df.sort_index(inplace=True)
afl_df['AVGATGDIFF'].fillna(0, inplace=True)

## Add per match game results from last three games

In [205]:
afl_df['goal_diff'] = afl_df['homeTeamScore.matchScore.goals'] - afl_df['awayTeamScore.matchScore.goals']


for index, row in df_all[df_all['match.status']=='CONCLUDED'].iterrows():
    if afl_df['goal_diff'][index] > 0:
        afl_df.at[index,'result'] = 3   # 3 is a win
    elif afl_df['goal_diff'][index] == 0:
        afl_df.at[index,'result'] = 2  # 2 is a draw
    else:
        afl_df.at[index,'result'] = 1  # 1 is a loss

In [206]:
afl_df.head()

,match.name,match.date,match.status,match.matchId,match.venue,match.utcStartTime,match.homeTeamId,match.awayTeamId,match.round,match.venueLocalStartTime,...,Time.on.Ground..,Substitute,group_id,date,HTGDIFF,ATGDIFF,AVGHTGDIFF,AVGATGDIFF,goal_diff,result
0,Carlton Vs Richmond,2017-03-23 08:20:00,CONCLUDED,CD_M20170140101,CD_V40,2017-03-23T08:20:00,CD_T30,CD_T120,CD_R201701401,2017-03-23T19:20:00,...,3600.0,0.0,0.0,2017-03-23 00:00:00,-6,6,0.0,0.0,-6,1.0
1,Collingwood Vs Western Bulldogs,2017-03-24 08:50:00,CONCLUDED,CD_M20170140102,CD_V40,2017-03-24T08:50:00,CD_T40,CD_T140,CD_R201701401,2017-03-24T19:50:00,...,3597.0,0.0,0.0,2017-03-24 00:00:00,-3,3,0.0,0.0,-3,1.0
2,St Kilda Vs Melbourne,2017-03-25 05:35:00,CONCLUDED,CD_M20170140103,CD_V190,2017-03-25T05:35:00,CD_T130,CD_T90,CD_R201701401,2017-03-25T16:35:00,...,3602.0,0.0,0.0,2017-03-25 00:00:00,-5,5,0.0,0.0,-5,1.0
3,Sydney Swans Vs Port Adelaide,2017-03-25 05:35:00,CONCLUDED,CD_M20170140104,CD_V60,2017-03-25T05:35:00,CD_T160,CD_T110,CD_R201701401,2017-03-25T16:35:00,...,0.0,0.0,0.0,0,-5,5,0.0,0.0,-5,1.0
4,Essendon Vs Hawthorn,2017-03-25 08:25:00,CONCLUDED,CD_M20170140106,CD_V40,2017-03-25T08:25:00,CD_T50,CD_T80,CD_R201701401,2017-03-25T19:25:00,...,3602.0,0.0,0.0,2017-03-25 00:00:00,5,-5,0.0,0.0,5,3.0

In [207]:
def previous_data(df, h_or_a_team, column, letter, past_n):
    """
    input: 
        df = dataframe with all results
        a_h_team = HomeTeam or AwayTeam
        column = column selected to get previous data from
    output:
        team_with_past_dict = dictionary with team as a key and columns as values with new 
                              columns with past value
    """
    d = dict()
    team_with_past_dict = dict()
    all_teams = df[h_or_a_team].unique()
    for team in all_teams:
        n_games = len(df[df[h_or_a_team]==team])
        team_with_past_dict[team] = df[df[h_or_a_team]==team]
        for i in range(1, past_n):
            d[i] = team_with_past_dict[team].assign(
                result=team_with_past_dict[team].groupby(h_or_a_team)[column].shift(i)
            ).fillna({'{}_X'.format(column): 0})
            team_with_past_dict[team]['{}_{}_{}'.format(letter, column, i)] = d[i].result
    return team_with_past_dict

In [208]:
def previous_data_call(df, side, column, letter, iterations):
    d = previous_data(df, side, column, letter, iterations)
    df_result= from_dict_value_to_df(d)
    df_result.sort_index(inplace=True)
    return df_result

In [209]:
df_last_home_results = previous_data_call(afl_df, 'match.homeTeam.name', 'result', 'H', 3)
df_last_away_results = previous_data_call(df_last_home_results, 'match.awayTeam.name', 'result', 'A', 3)

In [210]:
df_last_last_HTGDIFF_results = previous_data_call(df_last_away_results, 'match.homeTeam.name', 'HTGDIFF', 'H', 3)
df_last_last_ATGDIFF_results = previous_data_call(df_last_last_HTGDIFF_results, 'match.awayTeam.name', 'ATGDIFF', 'A', 3)

In [211]:
df_last_AVGFTHG_results = previous_data_call(df_last_last_ATGDIFF_results, 'match.homeTeam.name', 'AVGHTGDIFF', 'H', 2)
df_last_AVGFTAG_results = previous_data_call(df_last_AVGFTHG_results, 'match.awayTeam.name', 'AVGATGDIFF', 'A', 2)

In [212]:
afl_df = df_last_AVGFTAG_results.copy()

In [213]:
afl_df.shape

(990, 139)

In [214]:
afl_df

,match.name,match.date,match.status,match.matchId,match.venue,match.utcStartTime,match.homeTeamId,match.awayTeamId,match.round,match.venueLocalStartTime,...,H_result_1,H_result_2,A_result_1,A_result_2,H_HTGDIFF_1,H_HTGDIFF_2,A_ATGDIFF_1,A_ATGDIFF_2,H_AVGHTGDIFF_1,A_AVGATGDIFF_1
0,Carlton Vs Richmond,2017-03-23 08:20:00,CONCLUDED,CD_M20170140101,CD_V40,2017-03-23T08:20:00,CD_T30,CD_T120,CD_R201701401,2017-03-23T19:20:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Collingwood Vs Western Bulldogs,2017-03-24 08:50:00,CONCLUDED,CD_M20170140102,CD_V40,2017-03-24T08:50:00,CD_T40,CD_T140,CD_R201701401,2017-03-24T19:50:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,St Kilda Vs Melbourne,2017-03-25 05:35:00,CONCLUDED,CD_M20170140103,CD_V190,2017-03-25T05:35:00,CD_T130,CD_T90,CD_R201701401,2017-03-25T16:35:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Sydney Swans Vs Port Adelaide,2017-03-25 05:35:00,CONCLUDED,CD_M20170140104,CD_V60,2017-03-25T05:35:00,CD_T160,CD_T110,CD_R201701401,2017-03-25T16:35:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Essendon Vs Hawthorn,2017-03-25 08:25:00,CONCLUDED,CD_M20170140106,CD_V40,2017-03-25T08:25:00,CD_T50,CD_T80,CD_R201701401,2017-03-25T19:25:00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
985,Geelong Cats Vs GWS Giants,2021-09-03 09:50:00,CONCLUDED,CD_M20210142501,CD_V2925,2021-09-03T09:50:00,CD_T70,CD_T1010,CD_R202101425,2021-09-03T17:50:00,...,2.0,3.0,1.0,1.0,0.0,2.0,1.0,1.0,1.00,2.25
986,Brisbane Lions Vs Western Bulldogs,2021-09-04 09:20:00,CONCLUDED,CD_M20210142502,CD_V20,2021-09-04T09:20:00,CD_T20,CD_T140,CD_R202101425,2021-09-04T19:20:00,...,3.0,3.0,3.0,1.0,6.0,14.0,-4.0,4.0,5.25,2.50
987,Melbourne Vs Geelong Cats,2021-09-10 09:50:00,CONCLUDED,CD_M20210142601,CD_V2925,2021-09-10T09:50:00,CD_T90,CD_T70,CD_R202101426,2021-09-10T17:50:00,...,3.0,3.0,3.0,1.0,4.0,7.0,-7.0,2.0,1.50,2.75
988,Port Adelaide Vs Western Bulldogs,2021-09-11 09:40:00,CONCLUDED,CD_M20210142602,CD_V6,2021-09-11T09:40:00,CD_T110,CD_T140,CD_R202101426,2021-09-11T19:10:00,...,3.0,3.0,2.0,3.0,7.0,16.0,0.0,-4.0,5.75,0.75
989,Melbourne Vs Western Bulldogs,2021-09-25 09:15:00,CONCLUDED,CD_M20210142701,CD_V2925,2021-09-25T09:15:00,CD_T90,CD_T140,CD_R202101427,2021-09-25T17:15:00,...,3.0,3.0,1.0,2.0,13.0,4.0,11.0,0.0,5.00,2.75

In [215]:
df_matches_numeric = afl_df._get_numeric_data()

In [216]:
df_matches_numeric.columns

Index(['match.homeTeam.timeZone', 'match.awayTeam.timeZone', 'venue.capacity',
       'venue.groundDimension', 'venue.latitude', 'venue.longitude',
       'round.year', 'round.roundNumber', 'scoreWorm', 'scoreMap',
       'homeTeamScore.rushedBehinds', 'homeTeamScore.minutesInFront',
       'homeTeamScore.matchScore.totalScore', 'homeTeamScore.matchScore.goals',
       'homeTeamScore.matchScore.behinds',
       'homeTeamScore.matchScore.superGoals', 'awayTeamScore.rushedBehinds',
       'awayTeamScore.minutesInFront', 'awayTeamScore.matchScore.totalScore',
       'awayTeamScore.matchScore.goals', 'awayTeamScore.matchScore.behinds',
       'awayTeamScore.matchScore.superGoals', 'weather.tempInCelsius',
       'homeTeamScoreChart.goals', 'homeTeamScoreChart.leftBehinds',
       'homeTeamScoreChart.rightBehinds', 'homeTeamScoreChart.leftPosters',
       'homeTeamScoreChart.rightPosters', 'homeTeamScoreChart.rushedBehinds',
       'homeTeamScoreChart.touchedBehinds', 'awayTeamScoreChart.goals',
       'awayTeamScoreChart.leftBehinds', 'awayTeamScoreChart.rightBehinds',
       'awayTeamScoreChart.leftPosters', 'awayTeamScoreChart.rightPosters',
       'awayTeamScoreChart.rushedBehinds', 'awayTeamScoreChart.touchedBehinds',
       'Season', 'Local.start.time', 'Attendance', 'HQ1G', 'HQ1B', 'HQ2G',
       'HQ2B', 'HQ3G', 'HQ3B', 'HQ4G', 'HQ4B', 'Home.score', 'AQ1G', 'AQ1B',
       'AQ2G', 'AQ2B', 'AQ3G', 'AQ3B', 'AQ4G', 'AQ4B', 'Away.score', 'ID',
       'Kicks', 'Marks', 'Handballs', 'Goals', 'Behinds', 'Hit.Outs',
       'Tackles', 'Rebounds', 'Inside.50s', 'Clearances', 'Clangers',
       'Frees.For', 'Frees.Against', 'Brownlow.Votes', 'Contested.Possessions',
       'Uncontested.Possessions', 'Contested.Marks', 'Marks.Inside.50',
       'One.Percenters', 'Bounces', 'Goal.Assists', 'Time.on.Ground..',
       'Substitute', 'group_id', 'HTGDIFF', 'ATGDIFF', 'AVGHTGDIFF',
       'AVGATGDIFF', 'goal_diff', 'result', 'H_result_1', 'H_result_2',
       'A_result_1', 'A_result_2', 'H_HTGDIFF_1', 'H_HTGDIFF_2', 'A_ATGDIFF_1',
       'A_ATGDIFF_2', 'H_AVGHTGDIFF_1', 'A_AVGATGDIFF_1'],
      dtype='object')

In [217]:
#df_matches_numeric.drop(['match.homeTeam.timeZone', 'match.awayTeam.timeZone', 'goal_diff', 'result', 'homeTeamScore.matchScore.goals', 'awayTeamScore.matchScore.goals'], axis=1, inplace=True)


#df_matches_numeric = df_matches_numeric[['HTGDIFF','ATGDIFF','awayTeamScore.minutesInFront','homeTeamScore.minutesInFront','homeTeamScoreChart.goals','homeTeamScore.matchScore.totalScore','awayTeamScore.matchScore.totalScore','AVGHTGDIFF','round.year','awayTeamScoreChart.goals']]



df_matches_numeric.isnull().sum(axis = 0)

match.homeTeam.timeZone     0
match.awayTeam.timeZone     0
venue.capacity              0
venue.groundDimension       0
venue.latitude              0
                           ..
H_HTGDIFF_2                36
A_ATGDIFF_1                18
A_ATGDIFF_2                36
H_AVGHTGDIFF_1             18
A_AVGATGDIFF_1             18
Length: 99, dtype: int64

In [218]:
#df_norm = (df_matches_numeric - df_matches_numeric.min()) / (df_matches_numeric.max() - df_matches_numeric.min())

In [219]:
#df_norm.columns

In [220]:
predictable_columns = [
       'round.year', 'round.roundNumber', 'scoreWorm', 'scoreMap',
       'homeTeamScore.rushedBehinds', 'homeTeamScore.minutesInFront',
       'homeTeamScore.matchScore.totalScore', 'homeTeamScore.matchScore.goals',
       'homeTeamScore.matchScore.behinds',
       'homeTeamScore.matchScore.superGoals', 'awayTeamScore.rushedBehinds',
       'awayTeamScore.minutesInFront', 'awayTeamScore.matchScore.totalScore',
       'awayTeamScore.matchScore.goals', 'awayTeamScore.matchScore.behinds',
       'awayTeamScore.matchScore.superGoals', 'weather.tempInCelsius',
       'homeTeamScoreChart.goals', 'homeTeamScoreChart.leftBehinds',
       'homeTeamScoreChart.rightBehinds', 'homeTeamScoreChart.leftPosters',
       'homeTeamScoreChart.rightPosters', 'homeTeamScoreChart.rushedBehinds',
       'homeTeamScoreChart.touchedBehinds', 'awayTeamScoreChart.goals',
       'awayTeamScoreChart.leftBehinds', 'awayTeamScoreChart.rightBehinds',
       'awayTeamScoreChart.leftPosters', 'awayTeamScoreChart.rightPosters',
       'awayTeamScoreChart.rushedBehinds', 'awayTeamScoreChart.touchedBehinds', 
        'Attendance', 'HQ1G', 'HQ1B', 'HQ2G','HQ2B', 'HQ3G', 'HQ3B', 'HQ4G', 'HQ4B', 'Home.score', 'AQ1G', 'AQ1B',
       'AQ2G', 'AQ2B', 'AQ3G', 'AQ3B', 'AQ4G', 'AQ4B', 'Away.score', 'ID',
       'Kicks', 'Marks', 'Handballs', 'Goals', 'Behinds', 'Hit.Outs',
       'Tackles', 'Rebounds', 'Inside.50s', 'Clearances', 'Clangers',
       'Frees.For', 'Frees.Against', 'Brownlow.Votes', 'Contested.Possessions',
       'Uncontested.Possessions', 'Contested.Marks', 'Marks.Inside.50',
       'One.Percenters', 'Bounces', 'Goal.Assists', 'Time.on.Ground..',
       'Substitute', 'group_id', 'HTGDIFF', 'ATGDIFF', 'AVGHTGDIFF',
       'AVGATGDIFF', 'goal_diff', 'result', 'H_result_1', 'H_result_2',
       'A_result_1', 'A_result_2', 'H_HTGDIFF_1', 'H_HTGDIFF_2', 'A_ATGDIFF_1',
       'A_ATGDIFF_2', 'H_AVGHTGDIFF_1', 'A_AVGATGDIFF_1'
]

In [221]:

#

In [222]:

all_cols = ['match.matchId','match.date', 'match.status', 'match.venue', 'match.homeTeam.name', 'match.awayTeam.name','venue.name', 'venue.state', 'round.name', 'round.year', 'round.roundNumber', 'status',
'homeTeamScore.rushedBehinds', 'homeTeamScore.minutesInFront',
       'homeTeamScore.matchScore.totalScore', 'homeTeamScore.matchScore.goals',
       'homeTeamScore.matchScore.behinds',
       'homeTeamScore.matchScore.superGoals', 'awayTeamScore.rushedBehinds',
       'awayTeamScore.minutesInFront', 'awayTeamScore.matchScore.totalScore',
       'awayTeamScore.matchScore.goals', 'awayTeamScore.matchScore.behinds',
       'awayTeamScore.matchScore.superGoals', 'weather.tempInCelsius',
       'homeTeamScoreChart.goals', 'homeTeamScoreChart.leftBehinds',
       'homeTeamScoreChart.rightBehinds', 'homeTeamScoreChart.leftPosters',
       'homeTeamScoreChart.rightPosters', 'homeTeamScoreChart.rushedBehinds',
       'homeTeamScoreChart.touchedBehinds', 'awayTeamScoreChart.goals',
       'awayTeamScoreChart.leftBehinds', 'awayTeamScoreChart.rightBehinds',
       'awayTeamScoreChart.leftPosters', 'awayTeamScoreChart.rightPosters',
       'awayTeamScoreChart.rushedBehinds', 'awayTeamScoreChart.touchedBehinds', 
       'HQ1G', 'HQ1B', 'HQ2G',
       'HQ2B', 'HQ3G', 'HQ3B', 'HQ4G', 'HQ4B', 'Home.score', 'AQ1G', 'AQ1B',
       'AQ2G', 'AQ2B', 'AQ3G', 'AQ3B', 'AQ4G', 'AQ4B', 'Away.score',
       'Kicks', 'Marks', 'Handballs', 'Goals', 'Behinds', 'Hit.Outs',
       'Tackles', 'Rebounds', 'Inside.50s', 'Clearances', 'Clangers',
       'Frees.For', 'Frees.Against', 'Brownlow.Votes', 'Contested.Possessions',
       'Uncontested.Possessions', 'Contested.Marks', 'Marks.Inside.50',
       'One.Percenters', 'Bounces', 'Goal.Assists', 'Time.on.Ground..',
       'Substitute', 'group_id', 'HTGDIFF', 'ATGDIFF', 'AVGHTGDIFF',
       'AVGATGDIFF', 'goal_diff', 'result', 'H_result_1', 'H_result_2',
       'A_result_1', 'A_result_2', 'H_HTGDIFF_1', 'H_HTGDIFF_2', 'A_ATGDIFF_1',
       'A_ATGDIFF_2', 'H_AVGHTGDIFF_1', 'A_AVGATGDIFF_1']


non_feature_cols = ['match.date', 'match.status', 'match.venue', 'match.homeTeam.name', 'match.awayTeam.name','venue.name', 'venue.state', 'round.name', 'round.year', 'round.roundNumber', 'status']
feature_cols = [
       'homeTeamScore.rushedBehinds', 'homeTeamScore.minutesInFront',
       'homeTeamScore.matchScore.totalScore', 'homeTeamScore.matchScore.goals',
       'homeTeamScore.matchScore.behinds',
       'homeTeamScore.matchScore.superGoals', 'awayTeamScore.rushedBehinds',
       'awayTeamScore.minutesInFront', 'awayTeamScore.matchScore.totalScore',
       'awayTeamScore.matchScore.goals', 'awayTeamScore.matchScore.behinds',
       'awayTeamScore.matchScore.superGoals', 'weather.tempInCelsius',
       'homeTeamScoreChart.goals', 'homeTeamScoreChart.leftBehinds',
       'homeTeamScoreChart.rightBehinds', 'homeTeamScoreChart.leftPosters',
       'homeTeamScoreChart.rightPosters', 'homeTeamScoreChart.rushedBehinds',
       'homeTeamScoreChart.touchedBehinds', 'awayTeamScoreChart.goals',
       'awayTeamScoreChart.leftBehinds', 'awayTeamScoreChart.rightBehinds',
       'awayTeamScoreChart.leftPosters', 'awayTeamScoreChart.rightPosters',
       'awayTeamScoreChart.rushedBehinds', 'awayTeamScoreChart.touchedBehinds', 
       'HQ1G', 'HQ1B', 'HQ2G',
       'HQ2B', 'HQ3G', 'HQ3B', 'HQ4G', 'HQ4B', 'Home.score', 'AQ1G', 'AQ1B',
       'AQ2G', 'AQ2B', 'AQ3G', 'AQ3B', 'AQ4G', 'AQ4B', 'Away.score',
       'Kicks', 'Marks', 'Handballs', 'Goals', 'Behinds', 'Hit.Outs',
       'Tackles', 'Rebounds', 'Inside.50s', 'Clearances', 'Clangers',
       'Frees.For', 'Frees.Against', 'Brownlow.Votes', 'Contested.Possessions',
       'Uncontested.Possessions', 'Contested.Marks', 'Marks.Inside.50',
       'One.Percenters', 'Bounces', 'Goal.Assists', 'Time.on.Ground..',
       'Substitute', 'group_id', 'HTGDIFF', 'ATGDIFF', 'AVGHTGDIFF',
       'AVGATGDIFF', 'goal_diff', 'result', 'H_result_1', 'H_result_2',
       'A_result_1', 'A_result_2', 'H_HTGDIFF_1', 'H_HTGDIFF_2', 'A_ATGDIFF_1',
       'A_ATGDIFF_2', 'H_AVGHTGDIFF_1', 'A_AVGATGDIFF_1']

In [ ]:
# Define a function which returns a DataFrame with the expontential moving average for each numeric stat
def create_exp_weighted_avgs(df, span):
    # Create a copy of the df with only the game id and the team - we will add cols to this df
    ema_features = df[['game', 'team']].copy()
    
    feature_names = [col for col in df.columns if col.startswith('f_')] # Get a list of columns we will iterate over
    
    for feature_name in feature_names:
        feature_ema = (df.groupby('team')[feature_name]
                         .transform(lambda row: (row.ewm(span=span)
                                                    .mean()
                                                    .shift(1))))
        ema_features[feature_name] = feature_ema
    
    return ema_features

In [224]:
afl_df = afl_df[all_cols] 

afl_df = afl_df.rename(columns={col: 'f_' + col for col in afl_df if col not in non_feature_cols})

In [225]:
afl_df

,match.date,match.status,match.venue,match.homeTeam.name,match.awayTeam.name,venue.name,venue.state,round.name,round.year,round.roundNumber,...,f_H_result_1,f_H_result_2,f_A_result_1,f_A_result_2,f_H_HTGDIFF_1,f_H_HTGDIFF_2,f_A_ATGDIFF_1,f_A_ATGDIFF_2,f_H_AVGHTGDIFF_1,f_A_AVGATGDIFF_1
0,2017-03-23 08:20:00,CONCLUDED,CD_V40,Carlton,Richmond,MCG,VIC,Round 1,2017,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017-03-24 08:50:00,CONCLUDED,CD_V40,Collingwood,Western Bulldogs,MCG,VIC,Round 1,2017,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017-03-25 05:35:00,CONCLUDED,CD_V190,St Kilda,Melbourne,Marvel Stadium,VIC,Round 1,2017,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017-03-25 05:35:00,CONCLUDED,CD_V60,Sydney Swans,Port Adelaide,SCG,NSW,Round 1,2017,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2017-03-25 08:25:00,CONCLUDED,CD_V40,Essendon,Hawthorn,MCG,VIC,Round 1,2017,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
985,2021-09-03 09:50:00,CONCLUDED,CD_V2925,Geelong Cats,GWS Giants,Optus Stadium,WA,Semi Finals,2021,25,...,2.0,3.0,1.0,1.0,0.0,2.0,1.0,1.0,1.00,2.25
986,2021-09-04 09:20:00,CONCLUDED,CD_V20,Brisbane Lions,Western Bulldogs,Gabba,QLD,Semi Finals,2021,25,...,3.0,3.0,3.0,1.0,6.0,14.0,-4.0,4.0,5.25,2.50
987,2021-09-10 09:50:00,CONCLUDED,CD_V2925,Melbourne,Geelong Cats,Optus Stadium,WA,Preliminary Finals,2021,26,...,3.0,3.0,3.0,1.0,4.0,7.0,-7.0,2.0,1.50,2.75
988,2021-09-11 09:40:00,CONCLUDED,CD_V6,Port Adelaide,Western Bulldogs,Adelaide Oval,SA,Preliminary Finals,2021,26,...,3.0,3.0,2.0,3.0,7.0,16.0,0.0,-4.0,5.75,0.75
989,2021-09-25 09:15:00,CONCLUDED,CD_V2925,Melbourne,Western Bulldogs,Optus Stadium,WA,Grand Final,2021,27,...,3.0,3.0,1.0,2.0,13.0,4.0,11.0,0.0,5.00,2.75

In [157]:
df_X = df_norm[predictable_columns]

In [158]:
df_X.fillna(0,inplace=True)

In [33]:
# Normal Rounds have 9 games
# Round 24 has 4 games
# Round 25 and 26 have 2 games
# Round 27 has 1 game

# + 9 per match day for normal rounds

#int_for_test = len(df_all)
#int_for_prediction = int_for_test - 9

In [34]:
df_all.shape

(1196, 91)

In [35]:
#X = df_X.iloc[:int_for_prediction,:]
#print(X.shape)
#Y = df_all.iloc[:int_for_prediction,:]['result']
#print(Y.shape)
#Z = df_X.iloc[int_for_prediction:,:]
#print(Z.shape)

In [36]:
X = df_X
print(X.shape)
Y = df_all['result']
print(Y.shape)
#Z = df_X.iloc[int_for_prediction:,:]
#print(Z.shape)

(1196, 10)
(1196,)

In [37]:
#X = df_X.iloc[:int_for_prediction,:]
#print(X.shape)
#Y = df_all.iloc[:int_for_prediction,:]['result']
#print(Y.shape)
#Z = df_X.iloc[int_for_prediction:,:]
#print(Z.shape)

In [38]:
#df_next_games_teams = df_all.iloc[int_for_prediction:,:][['match.homeTeam.name', 'match.awayTeam.name']]
#print(df_next_games_teams.shape)

In [39]:
#df_next_games_teams

In [40]:
#df_all[['match.name','result']].tail(9)

In [41]:
df_next_games_teams

   match.homeTeam.name match.awayTeam.name
9     Western Bulldogs             Carlton
10        Sydney Swans        Geelong Cats
11         Collingwood      Adelaide Crows
12            Essendon      Brisbane Lions
13       Port Adelaide            Hawthorn
14     Gold Coast Suns           Melbourne
15     North Melbourne   West Coast Eagles
16            Richmond          GWS Giants
17           Fremantle            St Kilda

In [42]:
# how to make Z for test data

# loop through each new fixture team and get average of historical data? try this


Z = pd.DataFrame()




for index, row in df_next_games_teams.iterrows():
    home = row['match.homeTeam.name']
    away = row['match.awayTeam.name']
    tmp = df_all[(df_all['match.homeTeam.name']==home)&(df_all['match.awayTeam.name']==away)]
    tmp = tmp[predictable_columns].mean()
    #print("-----------")
    #print(tmp)
    #print("-----------")
    Z = Z.append({'HTGDIFF': tmp[0], 'ATGDIFF': tmp[1], 'awayTeamScore.minutesInFront': tmp[2], 'homeTeamScore.minutesInFront': tmp[3], 'homeTeamScoreChart.goals': tmp[4], 'homeTeamScore.matchScore.totalScore': tmp[5], 'awayTeamScore.matchScore.totalScore': tmp[6], 'AVGHTGDIF': tmp[7], 'round.year': 2022, 'awayTeamScoreChart.goals': tmp[9]}, ignore_index=True)

In [43]:
Z

,ATGDIFF,AVGHTGDIF,HTGDIFF,awayTeamScore.matchScore.totalScore,awayTeamScore.minutesInFront,awayTeamScoreChart.goals,homeTeamScore.matchScore.totalScore,homeTeamScore.minutesInFront,homeTeamScoreChart.goals,round.year
0,2.000000,-0.125000,-2.000000,83.000000,62.250000,12.000000,73.000000,50.250000,10.000000,2022.0
1,-4.000000,2.650000,4.000000,72.400000,46.000000,10.000000,94.000000,62.800000,14.000000,2022.0
2,2.500000,-2.625000,-2.500000,94.000000,66.000000,13.000000,72.500000,0.000000,10.500000,2022.0
3,0.500000,-1.437500,-0.500000,90.500000,59.000000,13.750000,91.750000,50.750000,13.250000,2022.0
4,-0.250000,2.875000,0.250000,84.000000,30.250000,12.500000,86.500000,86.250000,12.750000,2022.0
5,6.333333,-1.916667,-6.333333,122.333333,85.000000,17.666667,74.666667,29.666667,11.333333,2022.0
6,-2.000000,0.166667,2.000000,55.000000,41.666667,7.666667,66.666667,56.333333,9.666667,2022.0
7,-5.750000,2.187500,5.750000,55.750000,20.000000,7.500000,93.750000,83.250000,13.250000,2022.0
8,-2.666667,2.250000,2.666667,66.000000,21.000000,9.333333,79.666667,82.000000,12.000000,2022.0

In [44]:
X.to_pickle("pickle_files/X_2021.pkl")
Y.to_pickle("pickle_files/Y_2021.pkl")
Z.to_pickle("pickle_files/Z_2021.pkl")

df_2021 = pd.read_csv("data/afl_results_2021.csv")
df_next_games = df_2021[['match.homeTeam.name','match.awayTeam.name','homeTeamScore.matchScore.totalScore','awayTeamScore.matchScore.totalScore']][0:9]
df_next_games.to_pickle("pickle_files/next_games_2021.pkl")

In [45]:
df_next_games

,match.homeTeam.name,match.awayTeam.name,homeTeamScore.matchScore.totalScore,awayTeamScore.matchScore.totalScore
0,Richmond,Carlton,105,80
1,Collingwood,Western Bulldogs,53,69
2,Melbourne,Fremantle,80,58
3,Adelaide Crows,Geelong Cats,103,91
4,Essendon,Hawthorn,91,92
5,Brisbane Lions,Sydney Swans,94,125
6,North Melbourne,Port Adelaide,65,117
7,GWS Giants,St Kilda,78,86
8,West Coast Eagles,Gold Coast Suns,83,58